stages:
  - docker
  
build:
  stage: docker
  tags: 
    - shell
  except:
    - tags
  script:
    - docker build --pull --force-rm=true --tag=$(cat REPOSITORY)/docker/alpine-base .
    - docker push registry.timmertech.nl/docker/alpine-base
    # Remove from docker host
    - docker rmi registry.timmertech.nl/docker/alpine-base

release:
  stage: docker
  tags: 
    - shell
  only:
    - tags
  script:
    - docker build --pull --force-rm=true --tag=$(cat REPOSITORY)/docker/alpine-base:$(cat VERSION) .
    - docker push registry.timmertech.nl/docker/alpine-base:$(cat VERSION)
    # Remove from docker host
    - docker rmi registry.timmertech.nl/docker/alpine-base:$(cat VERSION)
