variables:
  REPOSITORY: registry.timmertech.nl

stages:
  - build
  - triggers
  
build:latest:
  stage: build
  only: 
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN ${REPOSITORY}
    - docker build --pull --force-rm=true 
        --build-arg VCS_REF=`git rev-parse --short HEAD` 
        --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` 
        --tag=${REPOSITORY}/${CI_PROJECT_PATH} .
    - docker push ${REPOSITORY}/${CI_PROJECT_PATH}

build:release:
  stage: build
  only:
    - tags
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN ${REPOSITORY}
    - docker build --pull --force-rm=true 
        --build-arg VCS_REF=`git rev-parse --short HEAD` 
        --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` 
        --tag=${REPOSITORY}/${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME} .
    - docker push ${REPOSITORY}/${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}

alpine-glibc:
  stage: triggers
  except:
    - tags
  before_script:
    - apk add --update --no-cache curl
  script:
    - curl -X POST -F token=71b1077ae91d5c69f6a46374cd80e9 -F ref=master https://gitlab.timmertech.nl/api/v3/projects/18/trigger/builds > /dev/null
    
alpine-redis:
  stage: triggers
  except:
    - tags
  before_script:
    - apk add --update --no-cache curl
  script:
    - curl -s -X POST -F token=bbd2dcdb2bcac6cda10e83d340be2f -F ref=master https://gitlab.timmertech.nl/api/v3/projects/4/trigger/builds > /dev/null

alpine-postgres:
  stage: triggers
  except:
    - tags
  before_script:
    - apk add --update --no-cache curl
  script:
    - curl -s -X POST -F token=057a8c4eefbdc9b9a9d146a5794169 -F ref=master https://gitlab.timmertech.nl/api/v3/projects/6/trigger/builds > /dev/null
