stages:
  - docker
  
build:
  stage: docker
  tags: 
    - shell
  except:
    - tags
  script:
    - docker build --pull --force-rm=true --tag=$(cat REPOSITORY)/${CI_PROJECT_PATH} .
    - docker push registry.timmertech.nl/${CI_PROJECT_PATH}
    # Remove from docker host
    - docker rmi registry.timmertech.nl/${CI_PROJECT_PATH}

release:
  stage: docker
  tags: 
    - shell
  only:
    - tags
  script:
    - docker build --pull --force-rm=true --tag=$(cat REPOSITORY)/${CI_PROJECT_PATH:$(cat VERSION) .
    - docker push registry.timmertech.nl/${CI_PROJECT_PATH}:$(cat VERSION)
    # Remove from docker host
    - docker rmi registry.timmertech.nl/${CI_PROJECT_PATH}:$(cat VERSION)
