#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.

ALPINE_VERSION=`docker run --rm -it alpine:latest head -1 /etc/alpine-release`

docker build \
		--build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
		--build-arg VCS_REF=`git rev-parse --short HEAD` \
		--build-arg DOCKER_IMAGE="${IMAGE_NAME}" \
		--build-arg ALPINE_VERSION="${ALPINE_VERSION}" \
		-t $IMAGE_NAME .

# EOF
